version: "3.9"

services:
  ani-gamer-plus:
    build:
      context: .
    image: anigamerplus:v1
    container_name: "aniGamerPlus"
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    restart: unless-stopped
